### ISSUE TITLE
Download links moved

### ISSUE THREAD

**Issue by fabianlupa** [larshp/nwabap751#4]
Hi, just to let you know: I think the download URLs for AS ABAP moved to the SAP store.

https://tools.hana.ondemand.com/#abap
https://store.sap.com/sap/cp/ui/resources/store/html/SolutionDetails.html?pid=0000014493&catID=&pcntry=DE&sap-language=EN&_cp_id=id-1477346420741-0

So probably cannot download them anymore using the dockerfile.

**Comment by larshp** [comment]
argh!

**Comment by larshp** [comment]
they moved the files due to legal reasons, so the docker file and guide will need to be changed to first download and then docker cp the files to the container
